vim.cmd("colorscheme catppuccin-macchiato")
require('transparent').clear_prefix('BufferLine')
require('transparent').clear_prefix('NeoTree')
require('transparent').clear_prefix('lualine')
require('transparent').clear_prefix('heirline')
